### ISSUE TITLE
Benchmarking eigen vector computation

### ISSUE THREAD

**Issue by eric-haibin-lin** [marekandreas/elpa#12]
I'm interested in benchmarking elpa's performance on computing the eigen vector of a matrix. I assume this (https://github.com/marekandreas/elpa/blob/master/python/examples/example.py) is the hello world program I should start with? If I want to use GPU, how do I modify this program for cuda matrix input? Thanks!

**Comment by eric-haibin-lin** [comment]
We're able to run example.py successfully. Now we're looking into how to run test/C/test.c...

**Comment by marekandreas** [comment]
When you build ELPA yourself, "make check" will compile all the test programs for you.
