### ISSUE TITLE
Configure erro on Ubuntu 22.04 with Intel  icc classic and ifort classic from oneAPI 2022.3  

### ISSUE THREAD

**Issue by alas-go** [marekandreas/elpa#19]
Hello, Sir/Madam.
The code  tells me  configuration error about  Fortran.  they have been attached .
Could you help ?
Thanks.

[Configure Erro.txt](https://github.com/marekandreas/elpa/files/9791308/Configure.Erro.txt)

**Comment by alas-go** [comment]
after specify CPP=“cpp -E”， Configuration is ok.
but when make -j, it prints the warnings about "ifort: warning #10315: specifying -lm before files may supersede the Intel(R) math library and affect performance" both -lm is in configure code or not

**Comment by marekandreas** [comment]
Dear @alas-go,

you can ignore this warning.
