### ISSUE TITLE
ELPA 2021.05.001.rc1: ELPA_2STAGE_REAL_GPU is missing if configured with --enable-gpu=yes

### ISSUE THREAD

**Issue by hfp** [marekandreas/elpa#2]
It is acknowledged that `--enable-gpu=yes` is legacy (given that other GPUs are starting to gain support in ELPA). However, it would be nice to carry-forward the previous set of PARAMETER values (or enumeration values) if a legacy configuration is still allowed. For Fortran code, the module can be used or the header file (constants) can be included. For the latter, one can check if for instance `ELPA_2STAGE_REAL_GPU` works (`#if defined(ELPA_2STAGE_REAL_GPU)`), but this is not straight-forward or possible with with a pure module file approach.

**This report is also about missing for instance `ELPA_2STAGE_REAL_GPU` if `--enable-gpu=no` is given at configuration time.** With the 2020-release of ELPA, this apparently worked, i.e., `ELPA_2STAGE_REAL_GPU` was part of the Fortran module. I wonder how this is ever valid for cross-compiled module files. Should support for an ELPA module file be dropped or should a request for `ELPA_2STAGE_REAL_GPU` be redirected to something else (fallback)?

This is an ask to keep the ELPA interface as stable as possible or to change it less frequently, or to (alternatively/finally) remove exposing internals of ELPA as part of the installed bits ("interface"). If for instance `elpa_constants.h` are exposed, they should be rather stable or not exist at all.

This issue can be of interest for the (upcoming) CP2K 8.2 (@mkrack @oschuett @dev-zero @alazzaro).

**Comment by marekandreas** [comment]
Dear @hfp,

this is indeed a bug if the GPU kernels are missing if "--enable-gpu" is specified. It was _intended_ that the old parameters still work for backward compatibility. I will have to check why this is not the case. The same is true for the parameters from the API

**Comment by hfp** [comment]
@marekandreas Thank you! Don't get worried, this was reported for an RC1. In fact, a hybrid approach can be taken if an application code is really that special or edges out the ELPA interface. The hybrid approach would be to using the module file *and* including a header like `elpa_constants.h`.

**Comment by marekandreas** [comment]
Is fixed with release candidate 2021.05.001.rc2

**Comment by hfp** [comment]
@marekandreas Thank you for the quick fix! Is RC2 somewhere available already?
