### ISSUE TITLE
Using other datatypes than double on GPUs

### ISSUE THREAD

**Issue by jeanlucf22** [marekandreas/elpa#20]
I have been successful in using ELPA2 on NVIDIA GPU for the type "double". However the same test code fails for other data types such as "float" with an error  
Assertion `error_elpa==ELPA_OK' failed
after the call to
elpa_eigenvectors_float(handle, a, ev, z, &error_elpa);
My understanding is that the only difference between the "double" version and the "float" version is the datatype of a, ev, and z, which should match the function call. But maybe I am missing something else?
I tried to use data (a, ev, z) on CPU and GPUs, with the same result.

**Comment by marekandreas** [comment]
Dear @jeanlucf22,

Is this error also present, when you use the generic name "elpa_eigenvectors" ? Note, that you can use this generic name, only if the data a, ev, and z is allocated on the host (i.e. not a GPU device pointer) and ELPA does handle all transfers.

**Comment by marekandreas** [comment]
Dear @jeanlucf22,

we cannot reproduce, this problem, also not with the current master. Can you try to upstream and test again?
And did you make sure that you have build ELPA  "--enable-single-precision" ?

**Comment by jeanlucf22** [comment]
Actually, it looks like if I call 
elpa_eigenvectors_float_complex(handle, a, ev, z, &error_elpa);
with a complex array as ev, and cast that array into a real array after the call (to get the eigenvalues), it works!
Is it what I am supposed to do? It is not clear to me, and the .h does not match such an interface...

**Comment by marekandreas** [comment]
Dear @jeanlucf22,

it is indeed an error on our side, that the elpa header contains the single precision definitions, even if ELPA has not been build with '--enable-single-precision'. This will be fixed in the upcoming November release.

Concerning your question with complex values: please be aware that, in an hermitian matrix the eigenvalues are always real! Hence even if the matrix (a) is complex, and you get complex (z) eigenvectors, the eigenvalues (ev) must be a real datatype, i.e. double or float respectively. This is also described in the documentation.
I hope this does solve all your problems?

**Comment by jeanlucf22** [comment]
I expect real eigenvalues, indeed. But it looks like if I use a real array for ev (as I understood it from the documentation), I get a failure. On the other hand, if I give a complex array for ev, it runs... I was wondering if that array was used internally as complex, or needed to be bigger than the matrix size?

**Comment by marekandreas** [comment]
Dear @jeanlucf22 ,

No, ev needs to be real (float or double)!

If you have a look at the source file of a C test (test/C/test.c), you will see that
`MATRIX_TYPE *a, *z;
 EV_TYPE *ev;
`
with
`MATRIX_TYPE complex float
EV_TYPE float` 
or 
`
MATRIX_TYPE complex double
EV_TYPE double
`
and
`
a  = calloc(na_rows*na_cols, sizeof(MATRIX_TYPE));
z  = calloc(na_rows*na_cols, sizeof(MATRIX_TYPE));
as = calloc(na_rows*na_cols, sizeof(MATRIX_TYPE));
ev = calloc(na, sizeof(EV_TYPE));
`

We cannot reproduce the behaviour you described. Did you run `make check TEST_FLAGS="na nev nblk"`  with na, nev, nblk from your setup ?

**Comment by marekandreas** [comment]
And could you report whether (after rebuilding with --enable-single-precision) the problem still appears on both CPU and GPU ?

**Comment by jeanlucf22** [comment]
I put a reproducer at
https://github.com/jeanlucf22/ELPA_test
It works with float and double, but not with complex (select case by uncommenting one #define between line 9 and 12 of main.c)

**Comment by marekandreas** [comment]
Dear @jeanlucf22,

the error had already been fixed in master_pre_stage, but not in master, hence the confusion about the reproducability. 
In any case, in the latest master, the problem should be fixed.
Can you verify this?

**Comment by jeanlucf22** [comment]
I confirm that the master branch now works for me. Thanks !
