### ISSUE TITLE
ELPA latest release requires CPP variable defined

### ISSUE THREAD

**Issue by toxa81** [marekandreas/elpa#21]
Here is the feedback from spack's pull-request https://github.com/spack/spack/pull/33439

You need to add a requirement for AC_PROG_CPP in the autotools

**Comment by marekandreas** [comment]
Thank you @toxa81 ,

I will have a look at this

**Comment by marekandreas** [comment]
Dear @toxa81 ,

the configure of ELPA has been updated, and the fix will be available in the upcoming 2022.11.001 release

**Comment by toxa81** [comment]
Great! Thank you very much @marekandreas ! I'll test the new version in spack and let you know.
