### ISSUE TITLE
nvidia-gpu cannot be set by exporting an environment variable in bash

### ISSUE THREAD

**Issue by vyu16** [marekandreas/elpa#24]
According to the [USERS_GUIDE](https://github.com/marekandreas/elpa/blob/master/documentation/USERS_GUIDE.md#v-influencing-default-values-with-environment-variables):

```
The user can change this default value by setting an enviroment variable to the desired value.

The name of this variable is always constructed in the following way:

ELPA_DEFAULT_tunable_parameter_name=value
```

(By the way environment is misspelled as enviroment.)

However, this doesn't seem to work well with the `nvidia-gpu`, `amd-gup`, and `intel-gpu` variables. Various online resources mentioned that it's not allowed to have a dash in the name of an environment variable. For example see [this post](https://stackoverflow.com/questions/62652094/how-to-create-shell-variable-with-dashes#:~:text=I%27ve%20never%20met%20a%20Bourne%2Dstyle%20shell%20that%20allowed%20%2D%20in%20a%20variable%20name.%20Only%20ASCII%20letters%20(of%20either%20case)%2C%20_%20and%20digits%20are%20supported%2C%20and%20the%20first%20character%20must%20not%20be%20a%20digit.) on stackoverflow.

So to work this around in bash, something like

```
env 'ELPA_DEFAULT_nvidia-gpu=1' ./test_elpa.x ...
```

is needed, instead of the more familar way, `export ELPA_DEFAULT_nvidia-gpu=1`.

It would be great if this could be clarified in the USERS_GUIDE, or even better, create`nvidia_gpu`, `amd_gpu`, and `intel_gpu` as aliases to the existing ones.

**Comment by marekandreas** [comment]
Dear @vyu16,
thank you for bringing this up. We will have a look at this

**Comment by marekandreas** [comment]
We have updated the documentation in ELPA 2022.11.001.rc2. Concerning the aliases with an "_" instead of "-", we will introduce this in the first release of 2023. It is to short time to accept this change still in the ELPA 2022.11.001. release.
