### ISSUE TITLE
Cannot build elpa-2022.11.001.rc1 with CUDA

### ISSUE THREAD

**Issue by vyu16** [marekandreas/elpa#25]
I downloaded elpa-2022.11.001.rc1 and tried the following:

```
cd elpa
mkdir build
cd build
../configure FC=ftn CC=cc CXX=CC --enable-nvidia-gpu --with-cuda-path=$CUDA_HOME --with-NVIDIA-GPU-compute-capability=sm_80 --disable-sse-assembly --disable-sse
make -j4
```

Ran into this error:

```
../src/elpa_api.F90:1117:2: fatal error: ./GPU/handle_destruction_template.F90: No such file or directory
```

Could it be that somebody forgot to commit the file `GPU/handle_destruction_template.F90`? I guess this also indicates a problem of the CI.

**Comment by marekandreas** [comment]
Dear @vyu16,
yes indeed this file had been forgotten in the EXTRA_DIST section, this is correct now and rc2 will be prepared soon
