### ISSUE TITLE
configure can't link to cublas

### ISSUE THREAD

**Issue by cruddybanana1102** [marekandreas/elpa#26]
[config.log](https://github.com/marekandreas/elpa/files/10190244/config.log)
 Trying to build elpa-2021.05.002 for my personal machine(Ubuntu 22.04 LTS) with Intel CORE(R) i7-9750H and NVIDIA GeForce GTX 1650. 
CUDA has been installed in /usr/local/cuda and nvcc --version works perfectly. /usr/local/cuda/lib64/libcublas.so also exists. But configure error can't link to cublas in the file. Please see attached config.log
Edit: attached screenshot

![Screenshot from 2022-12-09 04-24-48](https://user-images.githubusercontent.com/57914003/206584258-2567b7bb-ccb0-4bfd-90df-a7d245052cf7.png)

Thanks in advance

**Comment by knikhil1995** [comment]
From the config.log provided, the config line you used seems to be

../configure FC=mpif90 CC=mpicc FCFLAGS=-O2 -fPIC -mcpu=native CFLAGS=-O2 -fPIC -mcpu=native --enable-openmp --enable-nvidia-gpu --with-cuda-path=usr/local/cuda --with-cuda-sdk-path=usr/local/cuda --prefix=/home/cruddybanana1102/Downloads/elpa_dir/build LDFLAGS=-L/home/cruddybanana1102/Downloads/scalapack-2.2.0/lib -lscalapack -L//home/cruddybanana1102/Downloads/lapack-3.11.0 -llapack -L//home/cruddybanana1102/Downloads/OpenBLAS/install_dir/lib -lopenblas --disable-sse --disable-sse-assembly --disable-avx --disable-avx2 --disable-avx512 --enable-c-tests=no

I believe the cuda path should be /usr/local/cuda as opposed to usr/local/cuda (note the missing /)

**Comment by marekandreas** [comment]
Dear @cruddybanana1102, 

as @knikhil1995 pointed out, it seems that the path you specified to the cuda libraries, is not correct.
