### ISSUE TITLE
Build of C/C++ tests with CUDA failes for 2022.11.001.rc2

### ISSUE THREAD

**Issue by oschuett** [marekandreas/elpa#28]
Building the latest `2022.11.001.rc2` release with `--enable-nvidia-gpu=yes` fails with the following error message:

```
../test/C/test.c:171:10: fatal error: test/shared/GPU/test_gpu_vendor_agnostic_layerVariables.h: No such file or directory
  171 | #include "test/shared/GPU/test_gpu_vendor_agnostic_layerVariables.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

With `--disable-c-tests --disable-cpp-tests` the build succeeds.

**Comment by marekandreas** [comment]
Dear @oschuett ,

yes sth. got messed up with the relative paths. Will be corrected, asap.
