### ISSUE TITLE
Compilation error: "cannot find -ludev"

### ISSUE THREAD

**Issue by dbennett1994** [marekandreas/elpa#33]
Hello,

I am trying to compile elpa-2021.11.002 on my HPC cluster. I have the following modules loaded:

- intel/21.2.0
- intel-mkl/2021.2.0
- openmpi/4.1.1
- hwloc/1.11.8

Running make, the program compiles for a while, and eventually stops with this error:

```
GEN      libelpa.la
ld: cannot find -ludev
make[1]: *** [libelpa.la] Error 1
make[1]: Leaving directory `/net/fs2k02/srv/export/kaxiras/share_root/dbennett/elpa-2021.11.002/build'
make: *** [all] Error 2
```

I tried configuring using the instructions here, [here](https://xconfigure.readthedocs.io/en/latest/elpa/). Also, I tried just simply running configure, specifying the compilers and linking to scalapack following the instructions in INSTALL.md:

```
FC=mpifort CC=mpicc ../configure \
SCALAPACK_LDFLAGS="-L$MKL_HOME/lib/intel64 -lmkl_scalapack_lp64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_lp64 -lpthread -lm -Wl,-rpath,$MKL_HOME/lib/intel64" \
SCALAPACK_FCFLAGS="-L$MKL_HOME/lib/intel64 -lmkl_scalapack_lp64
-lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_lp64
-lpthread -lm -I$MKL_HOME/include/intel64/lp64"
```
But both give the same error. I couldn't find any reference to libudev in the code, and not really sure why it's being called.

Any advice much appreciated

Log files and configure script attached here

[config.txt](https://github.com/marekandreas/elpa/files/10864799/config.txt)
[configure-elpa-skx.txt](https://github.com/marekandreas/elpa/files/10864800/configure-elpa-skx.txt)
[make.txt](https://github.com/marekandreas/elpa/files/10864801/make.txt)

Thanks,

Daniel Bennett

**Comment by marekandreas** [comment]
Hello,

ELPA does not require libudev for building and/or runtime. This is also an error message neither we have ever encountered before nor any other user has reported it.
My feeling is, that this requirement comes in via your software stack on your HPC system...
I suggest that you could try two things:
- unload module hwloc
- have a look at the config.log after the configure step and search for "udev"; maybe you find where this comes in (if at all). If you do not find it, then this requirement comes from sure from your system software stack.
