### ISSUE TITLE
Could improve the compatiblity of elpa on AMD  Zen4 cpus machines

### ISSUE THREAD

**Issue by alas-go** [marekandreas/elpa#34]
Dear Sir/Madam.
Calculation of Bands implemented in QE AMD Zen4 cpus with Intel classic fortran  reports errors like below.
![image](https://user-images.githubusercontent.com/63892049/223007479-1dfd5228-d7c0-4b19-956d-1559f8ce98f2.png)

I don't know how to solve the bug.
Could you give some suggestion?

**Comment by marekandreas** [comment]
Dear @alas-go,

this error does not originate from ELPA. Please report this error to developers of the application calling ELPA.
We will only be able to help you, once an error in ELPA has been found/reported

**Comment by alas-go** [comment]
> 
Thanks for your reply.
Thanks.
