### ISSUE TITLE
configure issue in finding cublasDgemm 

### ISSUE THREAD

**Issue by phanimotamarri** [marekandreas/elpa#4]
I am trying to install ELPA 2021.05.001 using GNU C and Fortran compilers on a server with Intel Xeon Gold CPUs and NVIDIA V100 GPUs. For some reason the configure script is unable to find the library containing cublasDgemm even though it is able to detect "nvcc" as you can see in the screenshot attached.  All the CUDA paths are clearly specified as you can see in the attached config.log
Unable to understand what am I missing here!
[config.log](https://github.com/marekandreas/elpa/files/6735334/config.log)

<img width="1792" alt="Screenshot 2021-06-29 at 8 26 27 PM" src="https://user-images.githubusercontent.com/5560485/123843082-1db4a380-d92f-11eb-9a6c-5b74539b092d.png">

**Comment by marekandreas** [comment]
If you have a look at your config.log file you will see, that the error message states that "-lscalapack" cannot be found. Obviously sth. is wrong with the link-line you specified for scalapack
