### ISSUE TITLE
Is cholesky decomposition with gpusolver not implemented yet?

### ISSUE THREAD

**Issue by yizeyi18** [marekandreas/elpa#42]
### Issue
I compiled ELPA-2023.05.001 on my computer with a AMD MI50, and found the program fails all tests about cholesky decomposition on gpu with segmentation fault. Along the backtrace, it seems that the problem is caused by:

<details><summary>src/elpa_impl_generalized_transform_template.F90</summary>
This templete calls all-host-array routine without checking if the work is on GPU.
<pre>
117     if (.not. is_already_decomposed) then
118       ! B = U^T*U, B<-U
119       call self%elpa_cholesky_a_h_a_&
120           &ELPA_IMPL_SUFFIX&
121           &(b, error)
</pre>
</details>
<details><summary>src/cholesky/elpa_cholesky_template.F90</summary>
This templete checks work type by call obj%get("gpu_cholesky",gpu_cholesky, error) instead of checking macros about gpu, which made the a_h_a call from above tries to use GPU, then causing segmentation fault.
<pre>
157  call obj%get("gpu_cholesky",gpu_cholesky, error)
158  if (error .ne. ELPA_OK) then
159    write(error_unit,*) "ELPA_CHOLESKY: Problem getting option for gpu_cholesky. Aborting..."
160    success = .false.
161    return
162  endif
163
164  if (gpu_cholesky .eq. 1) then
165    useGPU = (gpu == 1)
166  else
167    useGPU = .false.
168  endif
</pre>
</details>

Would it be OK to simply add gpu-using check in either file, or there are some further work on gpusolver in progress? Options about gpusolver do not appear on INSTALL.md but do show in configure --help, is it useable for other routines(e.g. eigenvector) now?

### Detailed output
All outputs and call stack in the log file.
[validate_c_version_complex_double_generalized_1stage_gpu_random_default.sh.log](https://github.com/marekandreas/elpa/files/13060147/validate_c_version_complex_double_generalized_1stage_gpu_random_default.sh.log)

### Steps to reproduce the issue
Source the script below, make, and make check.
 
[Configure-amdclang.txt](https://github.com/marekandreas/elpa/files/13060159/Configure-amdclang.txt)

Using ROCmCC instead of hipcc to compile kernels on cpu written in C. It seems CXX could be simply replaced with hipcc to avoid editting Makefile, but not tested yet.

**Comment by yizeyi18** [comment]
UPDATE:
    Seems that both issues above is NOT the point rocsolver not working. 
    The point is in src/GPU/handle_creation_template.F90:
`obj%gpu_setup%gpusolverHandleArray(:) = obj%gpu_setup%rocblasHandleArray(:)`
simply add the line above to line 97 makes gpusolverHandleArray got initialised and all segmentation disappears.

**Comment by marekandreas** [comment]
Dear @yizeyi18,

thank you for this analysis. We have fixed it, it will be in the new release coming out ~2 weeks.
Btw. if you have not done so already: if you like ELPA please star this repo
