### ISSUE TITLE
Inconsistent checks for HAVE_SKEWSYMMETRIC in C headers

### ISSUE THREAD

**Issue by dmejiar** [marekandreas/elpa#44]
`elpa_generated.h` checks if `HAVE_SKEWSYMMETRIC` is defined, but the same check is not contained in `elpa_generic.h`, causing compilation issues.  I have a quick and dirty fix in this commit https://github.com/dmejiar/elpa/commit/7390e1256187589c4e6e0cfac1c15e75a1064902, but I am not sure this is the best way to handle the issue.

**Comment by marekandreas** [comment]
Dear @dmejiar,

thank you for notifying us about this and providing a possible "fix". We will check it asap.

**Comment by marekandreas** [comment]
Has been fixed. Will be in upcoming release 2023.11.001
