### ISSUE TITLE
Problem With mpiifort and mpiicc

### ISSUE THREAD

**Issue by jayamanlucky** [marekandreas/elpa#45]
1. cd elpa-master
2. ./autogen.sh
3. mkdir build
4. cd build
5. ../configure FC=mpiifx CC=mpiicx --prefix=/opt/elpa FCFLAGS="-O3 -xAVX2" CFLAGS="-O3 -xAVX2" --enable-option-checking=fatal SCALAPACK_LDFLAGS="-L/home/aarav/intel/mkl/2024.0/lib/intel64 -lmkl_scalapack_lp64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_lp64 -lpthread " SCALAPACK_FCFLAGS="-I/home/aarav/intel/mkl/2024.0/lib/intel64/lp64" --disable-avx512 --with-mpi=yes
6. error like this :- /usr/bin/ld: ./.libs/libelpatest.a(libelpatest_la-test_analytic.o): undefined reference to symbol 'mpi_gather_'
/usr/bin/ld: /home/aarav/intel/mpi/2021.11/lib/libmpifort.so.12: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:72450: validate_cpp_version_complex_double_eigenvalues_1stage_analytic] Error 1
make[1]: Leaving directory '/home/aarav/Videos/elpa-master/build'
make: *** [Makefile:68494: all] Error 2
 
log file attach
[config.log](https://github.com/marekandreas/elpa/files/13801251/config.log)

**Comment by terminationshock** [comment]
@jayamanlucky  I was able to reproduce the problem and will get back to you soon.

**Comment by terminationshock** [comment]
@jayamanlucky The solution is simple: You also have to set the C++ compiler with `CXX=mpiicpx`. Could you please try that and confirm that the error disappears?

**Comment by jayamanlucky** [comment]
its work
thank you so much
Testsuite summary for elpa 2023.11.001
============================================================================
# TOTAL: 311
# PASS:  202
# SKIP:  109
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0

**Comment by marekandreas** [comment]
Great that it works. If you like ELPA, please star the project.

**Comment by jayamanlucky** [comment]
1. cd elpa-master
2. ./autogen.sh
3. mkdir build
4. cd build
5. ../configure CXX=mpiicpc FC=mpiifort CC=mpiicc --prefix=/opt/elpa 'FCFLAGS=-O3 -xAVX2' 'CFLAGS=-O3 -xAVX2' --enable-option-checking=fatal 'SCALAPACK_LDFLAGS=-L/opt/intel/oneapi/mkl/2023.0.0/lib/intel64 -lmkl_scalapack_lp64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_lp64 -lpthread ' SCALAPACK_FCFLAGS=-I/opt/intel/oneapi/mkl/2023.0.0/lib/intel64/lp64 --enable-avx512 --with-mpi=yes
6. make
7. make check
8. Testsuite summary for elpa 2023.11.001
============================================================================
# TOTAL: 311
# PASS:  130
# SKIP:  109
# XFAIL: 0
# FAIL:  72
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to elpa-library@mpcdf.mpg.de
============================================================================
make[3]: *** [Makefile:84658: test-suite.log] Error 1
make[3]: Leaving directory '/home/aarav/wien2k/elpa/build'
make[2]: *** [Makefile:84766: check-TESTS] Error 2
make[2]: Leaving directory '/home/aarav/wien2k/elpa/build'
make[1]: *** [Makefile:90928: check-am] Error 2
make[1]: Leaving directory '/home/aarav/wien2k/elpa/build'
make: *** [Makefile:90930: check] Error 2
[config.log](https://github.com/marekandreas/elpa/files/14347705/config.log)
