### ISSUE TITLE
How to compile with AMD GPU and MPI?

### ISSUE THREAD

**Issue by jsboer** [marekandreas/elpa#49]
Hi, can ELPA be compiled with AMD GPU and MPI? I only find the way that compile mpi with CUDA in the INSTALL.md.

**Comment by marekandreas** [comment]
Yes, with sth. like this
`../configure CPP="gcc -E" CC=cc CXX=hipcc FC=ftn CXXFLAGS="-DROCBLAS_V3 -D__HIP_PLATFORM_AMD__ --offload-arch=gfx90a -g -O3 -std=c++17" CFLAGS="-g -O3 -std=c++17" LIBS="-lamdhip64 -fPIC" FCFLAGS="-g -O3"  --enable-option-checking=fatal --with-mpi=yes --disable-sse --disable-sse-assembly --disable-avx --disable-avx2 --disable-avx512 --enable-amd-gpu --enable-single-precision --enable-gpu-streams=amd --enable-hipcub --disable-cpp-tests --with-rocsolver`

**Comment by jsboer** [comment]
> Yes, with sth. like this `../configure CPP="gcc -E" CC=cc CXX=hipcc FC=ftn CXXFLAGS="-DROCBLAS_V3 -D__HIP_PLATFORM_AMD__ --offload-arch=gfx90a -g -O3 -std=c++17" CFLAGS="-g -O3 -std=c++17" LIBS="-lamdhip64 -fPIC" FCFLAGS="-g -O3" --enable-option-checking=fatal --with-mpi=yes --disable-sse --disable-sse-assembly --disable-avx --disable-avx2 --disable-avx512 --enable-amd-gpu --enable-single-precision --enable-gpu-streams=amd --enable-hipcub --disable-cpp-tests --with-rocsolver`

Hi, in this case, how do I pass the MPI environment to elpa? like MPI library and MPI include

**Comment by marekandreas** [comment]
This should be done automatically via the MPI-Fortran Compiler wrapper (in the above example it's CRAY's 'ftn' Fortran compiler wrapper)

**Comment by jsboer** [comment]
I got it, thank you!
