### ISSUE TITLE
Error when running ELPA build with the Nvidia GPU kernels on system without Cuda driver

### ISSUE THREAD

**Issue by mpijensen** [marekandreas/elpa#58]
**Description**
When building the ELPA library with the configure option '--enable-nvidia-gpu-kernels', ELPA will fail with the error "CUDA driver version is insufficient for CUDA runtime version" when running ELPA on a system that does not have a Cuda driver even with the ELPA parameter 'nvidia-gpu' set to 0.

**To Reproduce**
1. Choose a system with no CUDA driver.
2. ELPA version: 2024.03.001
3. Configure line:
`./configure --enable-shared --disable-static --prefix=/ --bindir=${prefix}/bin --sbindir=${prefix}/bin --libdir=${prefix}/lib --includedir=${prefix}/include --oldincludedir=${prefix}/include --enable-libtool-lock --enable-nvidia-gpu-kernels --with-NVIDIA-GPU-compute-capability=sm_70 --enable-openmp --with-threading-support-check-during-build=no --disable-sse --disable-sse-assembly --disable-avx --disable-avx2 --disable-avx512`
4. Build 
5. Run test "validate_split_comm_real_double"
6. See error :
  `./src/GPU/CUDA/./cudaFunctions_template.h:289 Error in cudaDeviceSynchronize: CUDA driver version is insufficient for CUDA runtime version
Error in executing  cudaGetLastErrorFrom: CUDA driver version is insufficient for CUDA runtime version
./src/GPU/CUDA/./cudaFunctions_template.h:135 Error in cudaGetLastError: unknown error
 elpa1_template: GPU error detected via gpu_get_last_error(). Aborting...`

**Expected behavior**
That ELPA could run on a system without a Cuda driver.

**How ELPA has been build:**
 - Compiler: GCC 12.2.0, 
 - System with no Cuda driver.
 - configure line: 
` ./configure --enable-shared --disable-static --prefix=/ --bindir=${prefix}/bin --sbindir=${prefix}/bin --libdir=${prefix}/lib --includedir=${prefix}/include --oldincludedir=${prefix}/include --enable-libtool-lock --enable-nvidia-gpu-kernels --with-NVIDIA-GPU-compute-capability=sm_70 --enable-openmp --with-threading-support-check-during-build=no --disable-sse --disable-sse-assembly --disable-avx --disable-avx2 --disable-avx512`

**Can the problem be reproduced with one of the ELPA test programs:**
 - Name of ELPA test-program: validate_split_comm_real_double

**Comment by marekandreas** [comment]
Dear @mpijensen ,

sorry for the delay in the reply. In deed what you have reported is a bug. This will be fixed and the corrected version will be available wit the next release, due in about 2-3 weeks. Until then: please do not compile for GPU usage, if no GPUs are available.

**Comment by mpijensen** [comment]
Dear @marekandreas 

Thank you for your reply. 

Will the fix make the 2024.05.001 release?
