### ISSUE TITLE
Build breaks for no apparent reason

### ISSUE THREAD

**Issue by yurivict** [marekandreas/elpa#8]
```2021.05.002_bugfix``` breaks with this [log](https://people.freebsd.org/~yuri/elpa-2021.05.002.b.log).

Configure environment:
```F77="gfortran10" FC="gfortran10" FFLAGS="-O -Wl,-rpath=/usr/local/lib/gcc10" FCFLAGS="-std=legacy -I/usr/local/include -I/disk-samsung/freebsd-ports/math/elpa/work/elpa-2021.05.002_bugfix -Isrc -Isrc/general -Wl,-rpath=/usr/local/lib/gcc10" MAKE=gmake ac_cv_path_PERL=/usr/local/bin/perl ac_cv_path_PERL_PATH=/usr/local/bin/perl  PERL_USE_UNSAFE_INC=1 XDG_DATA_HOME=/disk-samsung/freebsd-ports/math/elpa/work  XDG_CONFIG_HOME=/disk-samsung/freebsd-ports/math/elpa/work  XDG_CACHE_HOME=/disk-samsung/freebsd-ports/math/elpa/work/.cache  HOME=/disk-samsung/freebsd-ports/math/elpa/work PATH=/disk-samsung/freebsd-ports/math/elpa/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin SHELL=/bin/sh CONFIG_SHELL=/bin/sh ADDR2LINE="/usr/local/bin/addr2line" AR="/usr/local/bin/ar" AS="/usr/local/bin/as" CPPFILT="/usr/local/bin/c++filt" GPROF="/usr/local/bin/gprof" LD="/usr/local/bin/ld" NM="/usr/local/bin/nm" OBJCOPY="/usr/local/bin/objcopy" OBJDUMP="/usr/local/bin/objdump" RANLIB="/usr/local/bin/ranlib" READELF="/usr/local/bin/readelf" SIZE="/usr/local/bin/size" STRINGS="/usr/local/bin/strings" CMAKE_PREFIX_PATH="/usr/local" CONFIG_SITE=/disk-samsung/freebsd-ports/Templates/config.site lt_cv_sys_max_cmd_len=524288```

Configure arguments:
```
--disable-avx --disable-avx2 --disable-avx512  --disable-static  --disable-c-tests --without-mpi --disable-openmp --disable-sse --disable-sse-assembly --prefix=/usr/local ${_LATE_CONFIGURE_ARGS}
```

gcc-10
FreeBSD 13

**Comment by marekandreas** [comment]
From the log it seems that the command line arguments to CPP (and probably to the Fortran compiler) are broken. Can you provide the output of "V=1 make" ?

**Comment by yurivict** [comment]
```
$ V=1 gmake
gmake  all-am
gmake[1]: Entering directory '/disk-samsung/freebsd-ports/math/elpa/work/elpa-2021.05.002_bugfix'
/bin/sh ./libtool  --tag=FC   --mode=compile gfortran10 -DHAVE_CONFIG_H -I.   -fno-omit-frame-pointer -isystem /usr/local/include  -Imodules -Jmodules -Iprivate_modules -std=legacy -I/usr/local/include -I/disk-samsung/freebsd-ports/math/elpa/work/elpa-2021.05.002_bugfix -Isrc -Isrc/general -Wl,-rpath=/usr/local/lib/gcc10 -c -o src/libelpa_public_la-elpa.lo `test -f 'src/elpa.F90' || echo './'`src/elpa.F90
libtool: compile:  gfortran10 -DHAVE_CONFIG_H -I. -fno-omit-frame-pointer -isystem /usr/local/include -Imodules -Jmodules -Iprivate_modules -std=legacy -I/usr/local/include -I/disk-samsung/freebsd-ports/math/elpa/work/elpa-2021.05.002_bugfix -Isrc -Isrc/general -Wl,-rpath=/usr/local/lib/gcc10 -c src/elpa.F90  -fPIC
src/elpa.F90:338:7:

  338 |   use elpa_constants
      |       1
Fatal Error: Cannot open module file 'elpa_constants.mod' for reading at (1): No such file or directory
compilation terminated.
```

**Comment by yurivict** [comment]
Any idea why does it break?

**Comment by yurivict** [comment]
@marekandreas 

What generates ```elpa_constants.mod```?

**Comment by marekandreas** [comment]
elpa_constants.F90 contains a Fortran module which is used by several files of the API definition. The dependency checker realizes this and requires elpa_constants.F90 to be compiled (to elpa_constants.mod) before API files, like elpa_api.F90

**Comment by marekandreas** [comment]
I do not have any idea why the build fails, but I do _assume_ that the pre-processing of the files does not work correctly
